/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reflexion;

import java.awt.Color;
import java.awt.Graphics;
import static java.lang.Double.NaN;
import javax.swing.DefaultListModel;
import java.math.*;

/**
 *
 * @author super
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListMaterial = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        Material = new javax.swing.JTextField();
        Indice = new javax.swing.JTextField();
        Distancia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListIndice = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListDistancia = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        ListGrados = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        listH = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Grosor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Inclinacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Añadir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Graficar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 255));

        ListMaterial.setToolTipText("");
        jScrollPane4.setViewportView(ListMaterial);

        jLabel1.setText("Material");

        Material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaterialActionPerformed(evt);
            }
        });

        Indice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndiceActionPerformed(evt);
            }
        });

        Distancia.setNextFocusableComponent(Añadir);
        Distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanciaActionPerformed(evt);
            }
        });

        jLabel2.setText("Indice de refraccion");

        jLabel3.setText("Distancia");

        jScrollPane5.setViewportView(ListIndice);

        jScrollPane6.setViewportView(ListDistancia);

        ListGrados.setFocusable(false);
        jScrollPane8.setViewportView(ListGrados);

        listH.setFocusable(false);
        jScrollPane7.setViewportView(listH);

        jLabel7.setText("Grado de entrada");

        jLabel9.setText("Disrtancia Recorrida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Material, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(Indice, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        Grosor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrosorActionPerformed(evt);
            }
        });

        jLabel6.setText("Grosor del material");

        Inclinacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InclinacionActionPerformed(evt);
            }
        });

        jLabel4.setText("angulo incidente");

        Añadir.setText("Añadir");
        Añadir.setNextFocusableComponent(Material);
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel5.setText("Seleccionar solo el material");

        Graficar.setText("Graficar");
        Graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Grosor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Inclinacion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Eliminar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Graficar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Añadir)
                    .addComponent(Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inclinacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Grosor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Graficar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficarActionPerformed

        super.repaint();
    }//GEN-LAST:event_GraficarActionPerformed

    private void MaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaterialActionPerformed

    private void IndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndiceActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int index = ListMaterial.getSelectedIndex();

        modelMaterial.remove(index);
        modelIndice.remove(index);
        modelDistancia.remove(index);

        ListMaterial.setModel(modelMaterial);
        ListIndice.setModel(modelIndice);
        ListDistancia.setModel(modelDistancia);
    }//GEN-LAST:event_EliminarActionPerformed

    private void DistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaActionPerformed

    private void InclinacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InclinacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InclinacionActionPerformed

    public DefaultListModel getModelMaterial() {
        return modelMaterial;
    }

    public DefaultListModel getModelIndice() {
        return modelIndice;
    }

    public DefaultListModel getModelDistancia() {
        return modelDistancia;
    }

    DefaultListModel modelMaterial = new DefaultListModel();
    DefaultListModel modelIndice = new DefaultListModel();
    DefaultListModel modelDistancia = new DefaultListModel();


    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed

        try {
            Double.valueOf(Indice.getText());
            Integer.valueOf(Distancia.getText());

            modelMaterial.addElement(Material.getText());
            modelIndice.addElement(Indice.getText());
            modelDistancia.addElement(Distancia.getText());

            ListMaterial.setModel(modelMaterial);
            ListIndice.setModel(modelIndice);
            ListDistancia.setModel(modelDistancia);

            Material.setText("");
            Indice.setText("");
            Distancia.setText("");

            Indice.setBackground(Color.WHITE);
            Distancia.setBackground(Color.WHITE);
        } catch (Exception e) {
            Indice.setBackground(Color.red);
            Distancia.setBackground(Color.red);
            Indice.setText("");
            Distancia.setText("");
        }


    }//GEN-LAST:event_AñadirActionPerformed

    private void GrosorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrosorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrosorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JTextField Distancia;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Graficar;
    private javax.swing.JTextField Grosor;
    private javax.swing.JTextField Inclinacion;
    private javax.swing.JTextField Indice;
    private javax.swing.JList<String> ListDistancia;
    private javax.swing.JList<String> ListGrados;
    private javax.swing.JList<String> ListIndice;
    private javax.swing.JList<String> ListMaterial;
    private javax.swing.JTextField Material;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<String> listH;
    // End of variables declaration//GEN-END:variables
public void paint(Graphics g) {
        super.paint(g);

//  Creacion de cuadrados (Materiales)
        int x = 70;
        int y = 310;

        for (int i = 0; i < modelMaterial.getSize(); i++) {
            String strDistancia = (String) modelDistancia.getElementAt(i);

            double R = Math.random() * 255;
            double G = Math.random() * 255;
            double B = Math.random() * 255;

            g.setColor(new Color((int) R, (int) G, (int) B));
            g.fillRect(x, y, Integer.valueOf(strDistancia), Integer.valueOf(Grosor.getText()));//horizontal, vertical, largo, alto

            g.setColor(Color.BLACK);
String mate= (String)modelMaterial.getElementAt(i);
            g.drawString(mate, x, y);

            x = x + Integer.valueOf(strDistancia);
        }

// Creacion de linea Inicial
        double xi = 0;
        double yi = 0;

        double xf = 70;
        double yf = 0;

        if (modelMaterial.getSize() > 0) {
            yf = 310 + (Integer.valueOf(Grosor.getText()) / 2);

            xi = Math.sin(Integer.valueOf(Inclinacion.getText()) * (Math.PI / 180)) * 50;
            yi = Math.cos(Integer.valueOf(Inclinacion.getText()) * (Math.PI / 180)) * 50;

            //System.out.println(xi + "  " + yi + "  " + xf + "  " + yf);
            g.setColor(Color.RED);

            g.drawLine((int) (xf - xi), (int) (yf + yi), (int) xf, (int) yf);
            xi = xf;
            yi = yf;
        }

// Creacion de refraccion
        double iIndice = 1;
        double fIndice = 1;
        double Grado;
        try {
            Grado = Double.valueOf(Inclinacion.getText());
            DefaultListModel modelGrados = new DefaultListModel();
            DefaultListModel modelH = new DefaultListModel();

            for (int i = 0; i < modelMaterial.getSize(); i++) {
                String strDistancia = (String) modelDistancia.getElementAt(i);
                String strIndice = (String) modelIndice.getElementAt(i);

                iIndice = fIndice;
                fIndice = Double.valueOf(strIndice);
                //System.out.println("iIndice "+iIndice+"   fIndice  "+fIndice+"   Grado   "+Grado);
                double Grado1 = Grado;
                Grado = Math.asin((iIndice * Math.sin(Grado * (Math.PI / 180))) / (fIndice)) * (180 / Math.PI);

                 
                    
                 if(Grado>0) {
                    System.out.println("Respuesta " + Grado);
                    modelGrados.addElement(Grado);

                    xf = xi + Integer.valueOf(strDistancia);
                    double h = Integer.valueOf(strDistancia) / Math.cos(Grado * (Math.PI / 180));
                    System.out.println("h " + h);
                    modelH.addElement(h);
                    yf = yi - (h * Math.sin(Grado * (Math.PI / 180)));

                    System.out.println("yf  " + (h * Math.sin(Grado * (Math.PI / 180))));
                    System.out.println((int) xi + " " + (int) yi + " " + (int) xf + " " + (int) yf + "\n\n");

                    g.setColor(Color.red);
                    g.drawLine((int) xi, (int) yi, (int) xf, (int) yf);

                    xi = xf;
                    yi = yf;
                }else{
                    System.out.println("entreeeeeeeeeee");
                    Grado=Grado1;

                    System.out.println("Respuesta " + Grado);
                    modelGrados.addElement(Grado);

                    xf = xi - Integer.valueOf(strDistancia);
                    double h = Integer.valueOf(strDistancia) / Math.cos(Grado * (Math.PI / 180));
                    System.out.println("h " + h);
                    modelH.addElement(h);
                    yf = yi - (h * Math.sin(Grado * (Math.PI / 180)));

                    System.out.println("yf  " + (h * Math.sin(Grado * (Math.PI / 180))));
                    System.out.println((int) xi + " " + (int) yi + " " + (int) xf + " " + (int) yf + "\n\n");

                    g.setColor(Color.red);
                    g.drawLine((int) xi, (int) yi, (int) xf, (int) yf);

                    xi = xf;
                    yi = yf;


                    break;
}

//                System.out.println("Respuesta " + Grado);
//                modelGrados.addElement(Grado);
//
//                xf = xi + Integer.valueOf(strDistancia);
//                double h = Integer.valueOf(strDistancia) / Math.cos(Grado * (Math.PI / 180));
//                System.out.println("h " + h);
//                modelH.addElement(h);
//                yf = yi - (h * Math.sin(Grado * (Math.PI / 180)));
//
//                System.out.println("yf  " + (h * Math.sin(Grado * (Math.PI / 180))));
//                System.out.println((int) xi + " " + (int) yi + " " + (int) xf + " " + (int) yf + "\n\n");
//
//                g.setColor(Color.red);
//                g.drawLine((int) xi, (int) yi, (int) xf, (int) yf);
//
//                xi = xf;
//                yi = yf;
            }
            ListGrados.setModel(modelGrados);
            listH.setModel(modelH);
        } catch (Exception e) {

        }

    }
}
